development:
  adapter: redis
  url: redis://<%= ENV.fetch("REDIS_URL") { "localhost:6379/1" } %>

test:
  adapter: test

production:
  adapter: redis
  url: redis://<%= ENV.fetch("REDIS_URL") { "localhost:6379/1" } %>
  channel_prefix: ai_pay_production
