version: "3.8"
services:
  short-url-be:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - SHORT_URL_DATABASE_USER=postgres
      - SHORT_URL_DATABASE_PASSWORD=12345678
      - SHORT_URL_DATABASE_HOST=database
      - SHORT_URL_DATABASE=short_url
      - RAILS_ENV=development
    volumes:
      - ./:/workspace
    networks:
      - short-url-net-be
    restart: on-failure
    depends_on:
      - database

  database:
    image: postgis/postgis:14-3.2-alpine
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=short_url
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - short-url-net-be

networks:
  short-url-net-be:

volumes:
  postgres:
