version: "3.8"
services:
  short-url-be:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - SHORT_URL_DATABASE_USER=${SHORT_URL_DATABASE_USER}
      - SHORT_URL_DATABASE_PASSWORD=${SHORT_URL_DATABASE_PASSWORD}
      - SHORT_URL_DATABASE_HOST=${SHORT_URL_DATABASE_HOST}
      - SHORT_URL_DATABASE=${SHORT_URL_DATABASE}
      - RAILS_ENV=production
    volumes:
      - ./:/workspace
    networks:
      - short-url-net-be
    restart: on-failure
    depends_on:
      - database

  database:
    image: postgis/postgis:14-3.2-alpine
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${SHORT_URL_DATABASE}
      - POSTGRES_USER=${SHORT_URL_DATABASE_USER}
      - POSTGRES_PASSWORD=${SHORT_URL_DATABASE_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - short-url-net-be

networks:
  short-url-net-be:

volumes:
  postgres:
